version: '3'

services:
  db:
    image: mongo:latest

  adminmongo:
    image: mrvautin/adminmongo:latest
    links:
    - db
    environment:
      CONN_NAME: db
      DB_HOST: db
    ports:
    - ${ADMIN_PORT-8181}:1234


  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    links:
    - db
    volumes:
    - ./:/app
    ports:
    - ${PORT-8080}:3000
