version: '3'

services:
  db:
    image: mongo:latest
    ports:
    - 27017:27017

  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    links:
    - db
    volumes:
    - ./:/app
    ports:
    - 8080:3000
